name: "Build CLI"

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            suffix: linux-x64
            file: geode-x64
          - os: ubuntu-latest
            arch: aarch64
            suffix: linux-aarch64
            file: geode-aarch64
          - os: windows-latest
            arch: x64
            suffix: win-x64
            file: geode-x64.exe

    steps:
      - uses: actions/checkout@v4

      - name: graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          version: 'latest'

      - name: build w/ maven
        run: mvn package -Pnative

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build
          name: unstable build
          prerelease: true
          files: target/${{ matrix.file }}
          body: |
            auto builded from ${{ github.sha }}
            thats all
