name: "Build CLI"

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'

      - name: build w/ maven
        run: mvn package

      - name: release
        uses: softprops/actions-gh-release@v2
        with:
          tag_name: auto-build
          name: unstable build
          files: target/geode-*.jar
          body: |
            auto builded from ${{ github.sha }}
            thats all
