name: "Build CLI"

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            suffix: linux-x64
            file: geode
          - os: ubuntu-24.04-arm
            arch: aarch64
            suffix: linux-aarch64
            file: geode
          - os: windows-latest
            arch: x64
            suffix: win-x64.exe
            file: geode.exe

    steps:
      - uses: actions/checkout@v4

      - name: graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          version: 'latest'

      - name: cache
        uses: actions/cache@v4
        with:
          path: \~/.m2/repository
          key: \( {{ runner.os }}- \){{ matrix.suffix }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: musl
        run: sudo apt update && sudo apt install -y musl-tools

      - name: build w/ maven
        run: mvn package -Pnative -Dnative-image.build-args='-march=armv8-a --static --libc=musl'

      - name: rename files
        run: mv target/${{ matrix.file }} target/geode-${{ matrix.suffix }}

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build
          name: unstable build
          prerelease: true
          files: target/geode-${{ matrix.suffix }}
          body: |
            auto builded from ${{ github.sha }}
            thats all
